"""按软件分组的"几何联动参数"预设库。

这些参数在几何变化时通常跟着变（尺寸、坡度、标高、切割长度等）。
在设置页勾选后，比对时它们会被视为派生量：几何变化时这些参数联动变化
不提升为 Both（归为仅几何）。
"""

SOFTWARE_PRESETS = {
    "Revit": {
        "note": "Common Revit parameters that follow geometry",
        "props": [
            ("Span", "Beam span length"),
            ("Slope", "Beam/slab slope"),
            ("PitchAngle", "Slab pitch angle"),
            ("Cut Length", "Structural cut length"),
            ("Length", "Element length"),
            ("Width", "Element width"),
            ("Height", "Element height"),
            ("Area", "Element area"),
            ("Volume", "Element volume"),
            ("Perimeter", "Element perimeter"),
            ("Elevation at Bottom", "Base elevation"),
            ("Elevation at Top", "Top elevation"),
            ("Elevation at Bottom Survey", "Survey base elevation"),
            ("System Length", "MEP system run length"),
            ("Level Offset", "Offset from level"),
            ("Start Extension", "Geometric Position: start extension"),
            ("End Extension", "Geometric Position: end extension"),
            ("Start Join Cutback", "Steel connection cutback (start)"),
            ("End Join Cutback", "Steel connection cutback (end)"),
            ("Base Offset", "Base offset"),
            ("Top Offset", "Top offset"),
            ("Thickness", "Wall/floor thickness"),
            ("Unconnected Height", "Wall unconnected height"),
            ("Top Constraint", "Wall top constraint level"),
            ("Base Constraint", "Wall base constraint level"),
            ("NetSideArea", "Wall net side area"),
            ("GrossSideArea", "Wall gross side area"),
            ("NetFootPrintArea", "Wall footprint area"),
            ("GrossFootPrintArea", "Wall gross footprint area"),
            ("NetVolume", "Net volume"),
            ("GrossVolume", "Gross volume"),
            ("NetWeight", "Net weight"),
            ("GrossWeight", "Gross weight"),
            ("Surface Area", "Surface area"),
            ("Base Extension Distance", "Wall base extension distance"),
            ("Top Extension Distance", "Wall top extension distance"),
            ("Base is Attached", "Wall base is attached"),
            ("Top is Attached", "Wall top is attached"),
            ("Location Line", "Wall location line"),
            ("Cross-Section", "Wall cross-section (type)"),
            ("Family and Type", "Revit family and type"),
            ("Type Id", "Revit type id"),
            ("Rebar Cover - Exterior Face", "Rebar cover exterior face"),
            ("Rebar Cover - Interior Face", "Rebar cover interior face"),
            ("Rebar Cover - Other Faces", "Rebar cover other faces"),
            ("Estimated Reinforcement Volume", "Estimated reinforcement volume"),
        ],
    },
    "Civil 3D": {
        "note": "Common Civil 3D / InfraWorks parameters that follow geometry",
        "props": [
            ("Length", "Alignment/feature length"),
            ("Width", "Corridor/feature width"),
            ("Area", "Surface/feature area"),
            ("Perimeter", "Feature perimeter"),
            ("Slope", "Slope"),
            ("Grade", "Grade"),
            ("Cross Slope", "Cross slope"),
            ("Elevation", "Elevation"),
            ("Depth", "Depth"),
            ("Thickness", "Thickness"),
            ("Offset", "Offset"),
            ("Volume", "Volume"),
        ],
    },
    "Tekla Structures": {
        "note": "Common Tekla parameters that follow geometry",
        "props": [
            ("Length", "Part length"),
            ("Width", "Part width"),
            ("Height", "Part height"),
            ("Weight", "Part weight"),
            ("Volume", "Part volume"),
            ("Area", "Part area"),
            ("Cut Length", "Cut length"),
            ("Profile", "Profile"),
        ],
    },
    "Bentley (OpenBuildings)": {
        "note": "Common Bentley OpenBuildings parameters that follow geometry",
        "props": [
            ("Length", "Element length"),
            ("Width", "Element width"),
            ("Height", "Element height"),
            ("Area", "Element area"),
            ("Volume", "Element volume"),
            ("Elevation", "Elevation"),
            ("Offset", "Offset"),
            ("Slope", "Slope"),
        ],
    },
}
